travis:
  secure:
    BINSTAR_TOKEN: eSBUEHjn7ccyTEL9t4UnNhR8b4LVImjPa/QZWIoDxA8z7Wy82mdQaflglVdDligASORl/6v1Pioe1BiXs0VAgLvW+x2czzalhj1llvtxaaz9ilF1+34nt5TVe5BdfIfUPFLEJIrx4yGIdm5ZYp2BRci7ffaTWIbAnisO94loR+wy482gX48vr9imr5GqkA3Crrt/iDCjgtdS6EayLLi4raZ1sQSmZjhTc1YNRHpXL0c7rRLKkaVG+lBfmhiXRqf9TX3hJwgwCLkQbrQViOhgTFmITRf6B85w9QWVsCHn2cDXI9mfleo3Cu6tqKFxmD1z9n5ULhnuhVBtZ4IlWHKAMY89BkHLRiv6ijB5GdoczSgehuwBMlEe3+OSeXOLIlfaSr8TPWpb2A28vETAiglAp89/p6rC78wZdueYDqg5ia3mTUIqGdaNWRvbOJtqTmzesaMK8IcJgwjebZ0IXbUDH519eAc3JpTfVpGu0ZkefS7WGv+cA03UekxmM3N1fodNTpja6ty/nmJoXUMRRA4XUhAeVbeY0SP0LOsQnaWzImyNNkPhGzdgwsl26hTI/fCBeYslb4+vWpm4Q9D5RrVGuj4ls9Oj3VNfBw8xU+JVO9hnb2Gtgfo55ocXG4CzJLsiLVN3xJ8eEPhvxOqvbzSZa7X3GL9A4H0wlBoD2Ufa7ZI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
